title: Rudi - documentation
description: >
    La documentation de la plateforme Rudi

twitter_username: projetrudi
github_username:  sigrennesmetropole
github_repository: sigrennesmetropole/rudi_documentation
master_branch: main
url: https://sigrennesmetropole.github.io/rudi_documentation
lang: fr
permalink: pretty

i18n:
  en:
    edit: Edit this page
  fr:
    edit: Editer cette page

exclude:
  - .circle/
  - .idea/
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - README.md

# Collection configuration
# Specify a directory to store all our collections in the same place
collections_dir: articles

# Metadata for our collections
collections:
      
  glossaire:
    order: 1
    title: Glossaire
    output: true
     
  acces_donnees_restreintes:
    order: 2
    title: Accéder à des données restreintes
    output: true

   organisation:
    order: 3
    title: Organisations
    output: true
  
  api:
    order: 4
    title: API
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page

sass:
  style: compressed
